/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Farhad
 */
public class administration extends javax.swing.JFrame{

    /**
     * Creates new form administration
     */
    public administration() {
        initComponents();
    
    
    
    }
    String driver= "com.microsoft.sqlserver.jdbc.SQLServerDriver";
            String url= "jdbc:sqlserver://localhost\\dubai:1433;databaseName=travelmanagement";
            String user="sa";
            String pass="12345";
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mytable = new javax.swing.JTable();
        dubai = new javax.swing.JButton();
        thailand = new javax.swing.JButton();
        malaysia = new javax.swing.JButton();
        england = new javax.swing.JButton();
        india = new javax.swing.JButton();
        singapore = new javax.swing.JButton();
        usa = new javax.swing.JButton();
        coxsmartin = new javax.swing.JButton();
        nepal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mytable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mytable3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        userdetail = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rangamati = new javax.swing.JButton();
        bandarban = new javax.swing.JButton();
        sylhet = new javax.swing.JButton();
        sundarban = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        mytable1 = new javax.swing.JTable();
        airticket = new javax.swing.JButton();
        signinbtn2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_11red-wallpaper-1fd.jpg"))); // NOI18N

        mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User_ID", "Package_No", "Person", "Airways", "Ticket_Type", "Hotel", "Date_From"
            }
        ));
        jScrollPane1.setViewportView(mytable);
        if (mytable.getColumnModel().getColumnCount() > 0) {
            mytable.getColumnModel().getColumn(1).setHeaderValue("Package_No");
            mytable.getColumnModel().getColumn(4).setHeaderValue("Ticket_Type");
        }

        dubai.setText("Dubai");
        dubai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dubaiActionPerformed(evt);
            }
        });

        thailand.setText("Thailand");
        thailand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thailandActionPerformed(evt);
            }
        });

        malaysia.setText("Malaysia");
        malaysia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malaysiaActionPerformed(evt);
            }
        });

        england.setText("England");
        england.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englandActionPerformed(evt);
            }
        });

        india.setText("India");
        india.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiaActionPerformed(evt);
            }
        });

        singapore.setText("Singapore");
        singapore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singaporeActionPerformed(evt);
            }
        });

        usa.setText("USA");
        usa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usaActionPerformed(evt);
            }
        });

        coxsmartin.setText("Cox's Bazar & St. Martin");
        coxsmartin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coxsmartinActionPerformed(evt);
            }
        });

        nepal.setText("Nepal");
        nepal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nepalActionPerformed(evt);
            }
        });

        mytable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User_ID", "Package_No", "Person", "Airways_Type", "Bus_Type", "Hotel", "Date_From"
            }
        ));
        jScrollPane2.setViewportView(mytable2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("National Travel Bookings");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("International Travel Booking");

        mytable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Date_of_Birth", "User_ID", "Password", "Address", "City", "Country", "Contact_Number", "Favourite_Place"
            }
        ));
        jScrollPane3.setViewportView(mytable3);

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User Details");

        userdetail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userdetail.setText("Check User Details");
        userdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userdetailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Admin Home");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_admin_logo_by_lucifercho-d39lpuk.png"))); // NOI18N

        rangamati.setText("Rangamati");
        rangamati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangamatiActionPerformed(evt);
            }
        });

        bandarban.setText("Bandarban");
        bandarban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandarbanActionPerformed(evt);
            }
        });

        sylhet.setText("Sylhet & Jaflong");
        sylhet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sylhetActionPerformed(evt);
            }
        });

        sundarban.setText("Sundarbans");
        sundarban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundarbanActionPerformed(evt);
            }
        });

        mytable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User_ID", "Country", "Person", "Airways", "Ticket_Type", "Travel Date"
            }
        ));
        jScrollPane4.setViewportView(mytable1);
        if (mytable1.getColumnModel().getColumnCount() > 0) {
            mytable1.getColumnModel().getColumn(1).setHeaderValue("Package_No");
            mytable1.getColumnModel().getColumn(4).setHeaderValue("Ticket_Type");
        }

        airticket.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        airticket.setText("Check");
        airticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airticketActionPerformed(evt);
            }
        });

        signinbtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signinbtn2.setText("Sign-in");
        signinbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn2ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 153, 153));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Airways Booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dubai, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(thailand))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(england, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(india, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(singapore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nepal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(malaysia, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(173, 173, 173)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(airticket)))
                            .addGap(287, 287, 287)
                            .addComponent(signinbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userdetail))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(306, 306, 306)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coxsmartin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bandarban)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sundarban)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rangamati, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sylhet)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(signinbtn2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airticket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(thailand)
                                    .addComponent(dubai)
                                    .addComponent(malaysia)
                                    .addComponent(usa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(india)
                                    .addComponent(england)
                                    .addComponent(singapore)
                                    .addComponent(nepal)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coxsmartin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bandarban, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sundarban, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rangamati, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sylhet, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dubaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dubaiActionPerformed
                
       
      
 try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from dubai");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    
    
           
            
                    
                       
        

// TODO add your handling code here:
    }//GEN-LAST:event_dubaiActionPerformed

    private void thailandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thailandActionPerformed
      
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from thailand");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }
    


// TODO add your handling code here:
    }//GEN-LAST:event_thailandActionPerformed

    private void malaysiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malaysiaActionPerformed


              try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from malaysia");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_malaysiaActionPerformed

    private void englandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englandActionPerformed


              try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from uk");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_englandActionPerformed

    private void indiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiaActionPerformed


                  try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from india");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_indiaActionPerformed

    private void singaporeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singaporeActionPerformed


                      try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from singapore");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_singaporeActionPerformed

    private void usaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usaActionPerformed


                  try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from usa");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_usaActionPerformed

    private void coxsmartinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coxsmartinActionPerformed
                 try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from coxsbazar_st_martin");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable2.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }

                        // TODO add your handling code here:
    }//GEN-LAST:event_coxsmartinActionPerformed

    private void nepalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nepalActionPerformed
                
  try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from nepal");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_nepalActionPerformed

    private void userdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userdetailActionPerformed
      
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from sign_up");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable3.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }

// TODO add your handling code here:
    }//GEN-LAST:event_userdetailActionPerformed

    private void rangamatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangamatiActionPerformed


                          try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from rangamati");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable2.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_rangamatiActionPerformed

    private void bandarbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandarbanActionPerformed
            
           try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from bandarban");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable2.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }       
        // TODO add your handling code here:
    }//GEN-LAST:event_bandarbanActionPerformed

    private void sylhetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sylhetActionPerformed


                  try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from sylhet");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable2.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }
                    // TODO add your handling code here:
    }//GEN-LAST:event_sylhetActionPerformed

    private void sundarbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundarbanActionPerformed


                  try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from sundarban");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable2.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_sundarbanActionPerformed

    private void airticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airticketActionPerformed

                             try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                     
            String stringCon = "jdbc:sqlserver://localhost:1433;databaseName=travelmanagement;user=sa;password=12345";
            Connection con = DriverManager.getConnection(stringCon);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from airticket");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            int column = rsmetadata.getColumnCount();
            
            DefaultTableModel dtm = new DefaultTableModel();
            
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();
            for(int i=1;i<column;i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);
            while(rs.next()){
                
                data_rows = new Vector();
                for(int j=1;j<column;j++){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);
                mytable1.setModel(dtm);
            }
            
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(administration.class.getName()).log(Level.SEVERE, null, ex);
            }  

                    // TODO add your handling code here:
    }//GEN-LAST:event_airticketActionPerformed

    private void signinbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn2ActionPerformed
                adminsignin adsign = new adminsignin();
                this.dispose();
                adsign.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_signinbtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airticket;
    private javax.swing.JButton bandarban;
    private javax.swing.JButton coxsmartin;
    private javax.swing.JButton dubai;
    private javax.swing.JButton england;
    private javax.swing.JButton india;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton malaysia;
    private javax.swing.JTable mytable;
    private javax.swing.JTable mytable1;
    private javax.swing.JTable mytable2;
    private javax.swing.JTable mytable3;
    private javax.swing.JButton nepal;
    private javax.swing.JButton rangamati;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JButton signinbtn2;
    private javax.swing.JButton singapore;
    private javax.swing.JButton sundarban;
    private javax.swing.JButton sylhet;
    private javax.swing.JButton thailand;
    private javax.swing.JButton usa;
    private javax.swing.JButton userdetail;
    // End of variables declaration//GEN-END:variables
}
