/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Farhad
 */
public class indiapack extends javax.swing.JFrame {

    /**
     * Creates new form indiapack
     */
    public indiapack() {
        initComponents();
    }

    String driver= "com.microsoft.sqlserver.jdbc.SQLServerDriver";
            String url= "jdbc:sqlserver://localhost\\india:1433;databaseName=travelmanagement";
            String user="sa";
            String pass="12345";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        backbtn3 = new javax.swing.JButton();
        homebtn3 = new javax.swing.JButton();
        pediabtn5 = new javax.swing.JButton();
        airwaysbtn5 = new javax.swing.JButton();
        signinbtn5 = new javax.swing.JButton();
        hotelbtn5 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        useridtxt3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        packnotxt3 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        personnotxt3 = new javax.swing.JTextField();
        hotelcomb = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        aircombo3 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ticketcombo3 = new javax.swing.JComboBox<>();
        datefrom3 = new com.toedter.calendar.JDateChooser();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtReceipt3 = new javax.swing.JTextArea();
        printbtn3 = new javax.swing.JButton();
        submitbtn3 = new javax.swing.JButton();
        aboutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(958, 600));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_11red-wallpaper-1fd.jpg"))); // NOI18N

        backbtn3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backbtn3.setText("Back");
        backbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn3ActionPerformed(evt);
            }
        });

        homebtn3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        homebtn3.setText("Home");
        homebtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtn3ActionPerformed(evt);
            }
        });

        pediabtn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pediabtn5.setText("Tour Pedia");
        pediabtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pediabtn5ActionPerformed(evt);
            }
        });

        airwaysbtn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        airwaysbtn5.setText("Airways");
        airwaysbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airwaysbtn5ActionPerformed(evt);
            }
        });

        signinbtn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signinbtn5.setText("Sign-in");
        signinbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn5ActionPerformed(evt);
            }
        });

        hotelbtn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hotelbtn5.setText("Hotel");
        hotelbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelbtn5ActionPerformed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("User ID");

        useridtxt3.setBackground(new java.awt.Color(255, 255, 255));
        useridtxt3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Package No.");

        packnotxt3.setBackground(new java.awt.Color(255, 255, 255));
        packnotxt3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Total Persons");

        personnotxt3.setBackground(new java.awt.Color(255, 255, 255));
        personnotxt3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        personnotxt3.setForeground(new java.awt.Color(0, 0, 0));

        hotelcomb.setBackground(new java.awt.Color(255, 255, 255));
        hotelcomb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hotelcomb.setForeground(new java.awt.Color(51, 51, 51));
        hotelcomb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "The Oberoi Amarvilas", "The Oberoi Rajvilas" }));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Hotel");

        aircombo3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aircombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Airways", "Biman Bangladesh", "Emirates", "United Airways", "Thai Airways", "Kuwait Airways", "Malaysia Airways", "Bengal Airways", "Singapore Airlines", "Dragon Air" }));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Airways");

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Ticket Type");

        ticketcombo3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ticketcombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Economy Class", "Business Class", "Luxury" }));

        datefrom3.setBackground(new java.awt.Color(255, 255, 255));
        datefrom3.setForeground(new java.awt.Color(0, 0, 0));
        datefrom3.setDateFormatString("yyyy-MM-dd");

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Travel Date");

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("From");

        jtxtReceipt3.setBackground(new java.awt.Color(255, 255, 255));
        jtxtReceipt3.setColumns(20);
        jtxtReceipt3.setForeground(new java.awt.Color(0, 0, 0));
        jtxtReceipt3.setRows(5);
        jScrollPane5.setViewportView(jtxtReceipt3);

        printbtn3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        printbtn3.setText("Print");
        printbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtn3ActionPerformed(evt);
            }
        });

        submitbtn3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        submitbtn3.setText("Submit");
        submitbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtn3ActionPerformed(evt);
            }
        });

        aboutbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        aboutbtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutbtn.setText("About");
        aboutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(backbtn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(submitbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(printbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(aboutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(homebtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pediabtn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(airwaysbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signinbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hotelbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useridtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(packnotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(personnotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addComponent(aircombo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(hotelcomb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ticketcombo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel37))
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datefrom3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38))
                                .addGap(70, 70, 70)))))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homebtn3)
                    .addComponent(pediabtn5)
                    .addComponent(airwaysbtn5)
                    .addComponent(signinbtn5)
                    .addComponent(hotelbtn5)
                    .addComponent(backbtn3)
                    .addComponent(aboutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(useridtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(packnotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelcomb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personnotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ticketcombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aircombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(datefrom3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39))))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtn3ActionPerformed

        packageselect pct = new packageselect();
        this.dispose();
        pct.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_homebtn3ActionPerformed

    private void pediabtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pediabtn5ActionPerformed
tourpedia tpda =new tourpedia();
            this.dispose();
            tpda.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pediabtn5ActionPerformed

    private void airwaysbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airwaysbtn5ActionPerformed

        airticket act = new airticket();
        this.dispose();
        act.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_airwaysbtn5ActionPerformed

    private void signinbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn5ActionPerformed

        signin sin = new signin();
        this.dispose();
        sin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_signinbtn5ActionPerformed

    private void hotelbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelbtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelbtn5ActionPerformed

    private void aboutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutbtnActionPerformed

        about at = new about();
        this.dispose();
        at.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutbtnActionPerformed

    private void submitbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtn3ActionPerformed
 
      
        try {
          
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            Statement stmt = con.createStatement();
            String sql= "insert into india"
                    +"(User_ID,Package_No,Person,Airways,Ticket_Type,Hotel,Date_From)"
                    +"values(?,?,?,?,?,?,?)";
            PreparedStatement pst= con.prepareStatement(sql);
            pst.setString(1,useridtxt3.getText());
            pst.setString(2,packnotxt3.getText());
            pst.setString(3,personnotxt3.getText());
            String value = aircombo3.getSelectedItem().toString();
            pst.setString(4,value);
            String values = ticketcombo3.getSelectedItem().toString();
            pst.setString(5,values);
            String valuess = hotelcomb.getSelectedItem().toString();
            pst.setString(6,valuess);
            pst.setString(7,((JTextField)datefrom3.getDateEditor().getUiComponent()).getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Booked Successfully");
            
                
                        
                        
// TODO add your handling code here:
        } catch(HeadlessException | ClassNotFoundException | SQLException e)
                {
                      JOptionPane.showMessageDialog(this,e.getMessage()); 
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_submitbtn3ActionPerformed

    private void printbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtn3ActionPerformed


            String rUserid =(useridtxt3.getText());
            String rPackageno=(packnotxt3.getText());
            String rPerson=(personnotxt3.getText());
            String rAirways = aircombo3.getSelectedItem().toString();
            String rTicket = ticketcombo3.getSelectedItem().toString();
            String rHotel = hotelcomb.getSelectedItem().toString();
            String rDate = ((JTextField)datefrom3.getDateEditor().getUiComponent()).getText();
      	
        jtxtReceipt3.append("\tAsian Holidays Ltd. \n\n"  
        
        +"\n\n\tUser ID: "+ rUserid
        +"\n\n\tSelected Package: "+ rPackageno
        +"\n\n\tTotal Person: "+ rPerson
        +"\n\n\tSelected Airways: "+ rAirways
        +"\n\n\tTicket Type: "+ rTicket 
        +"\n\n\tSelected Hotel: "+ rHotel
        +"\n\n\tTraveling Date: "+ rDate 
       
        
        +"\n\n\n\tThanks for Choosing us"
        
        
     );         // TODO add your handling code here:
    }//GEN-LAST:event_printbtn3ActionPerformed

    private void backbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn3ActionPerformed

        india inb = new india();
        this.dispose();
        inb.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_backbtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(indiapack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(indiapack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(indiapack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(indiapack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new indiapack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutbtn;
    private javax.swing.JComboBox<String> aircombo3;
    private javax.swing.JButton airwaysbtn5;
    private javax.swing.JButton backbtn3;
    private com.toedter.calendar.JDateChooser datefrom3;
    private javax.swing.JButton homebtn3;
    private javax.swing.JButton hotelbtn5;
    private javax.swing.JComboBox<String> hotelcomb;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jtxtReceipt3;
    private javax.swing.JTextField packnotxt3;
    private javax.swing.JButton pediabtn5;
    private javax.swing.JTextField personnotxt3;
    private javax.swing.JButton printbtn3;
    private javax.swing.JButton signinbtn5;
    private javax.swing.JButton submitbtn3;
    private javax.swing.JComboBox<String> ticketcombo3;
    private javax.swing.JTextField useridtxt3;
    // End of variables declaration//GEN-END:variables
}
