/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;



/**
 *
 * @author Farhad
 */
public class packageselect extends javax.swing.JFrame {

    
    
       double Dollar=0.012;
       double Pound=0.76;
       double Rupi=0.77;
       double Ringgit=0.049;
       double Baht=0.39;
       double Rupee=1.23;
       double sDollar=0.016;
       double Dirham=0.044;
    /**
     * Creates new form packageselect
     */
       
   
    public packageselect() {
      initComponents();  
    }
  
    
    
    String driver= "com.microsoft.sqlserver.jdbc.SQLServerDriver";
            String url= "jdbc:sqlserver://localhost\\dubai:1433;databaseName=travel";
            String user="sa";
            String pass="12345";


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tpackbtn = new javax.swing.JButton();
        airticketbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jlblConvert = new javax.swing.JButton();
        convertionclose = new javax.swing.JButton();
        jcmbcurrency = new javax.swing.JComboBox<>();
        convert = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        converted = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        pediabtn2 = new javax.swing.JButton();
        airwaysbtn2 = new javax.swing.JButton();
        signinbtn2 = new javax.swing.JButton();
        aboutbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_11red-wallpaper-1fd.jpg"))); // NOI18N

        tpackbtn.setBackground(new java.awt.Color(255, 102, 102));
        tpackbtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tpackbtn.setText("Click Here");
        tpackbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tpackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpackbtnActionPerformed(evt);
            }
        });

        airticketbtn.setBackground(new java.awt.Color(255, 102, 102));
        airticketbtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        airticketbtn.setText("Click Here");
        airticketbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        airticketbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airticketbtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        jlblConvert.setBackground(new java.awt.Color(63, 168, 249));
        jlblConvert.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblConvert.setText("Convert");
        jlblConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblConvertActionPerformed(evt);
            }
        });

        convertionclose.setBackground(new java.awt.Color(0, 153, 204));
        convertionclose.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        convertionclose.setText("Close");
        convertionclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertioncloseActionPerformed(evt);
            }
        });

        jcmbcurrency.setBackground(new java.awt.Color(255, 255, 255));
        jcmbcurrency.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcmbcurrency.setForeground(new java.awt.Color(51, 51, 51));
        jcmbcurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One", "USA", "England", "India", "Nepal", "Thailand", "Malaysia", "Dubai", "Singapore" }));

        convert.setBackground(new java.awt.Color(255, 255, 255));
        convert.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        convert.setForeground(new java.awt.Color(0, 0, 0));

        converted.setBackground(new java.awt.Color(255, 255, 255));
        converted.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane6.setViewportView(converted);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Currency Converter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcmbcurrency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(convert)
            .addComponent(jScrollPane6)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlblConvert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(convertionclose, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jcmbcurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblConvert)
                    .addComponent(convertionclose)))
        );

        pediabtn2.setBackground(new java.awt.Color(255, 102, 102));
        pediabtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pediabtn2.setText("Tour Pedia");
        pediabtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pediabtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pediabtn2ActionPerformed(evt);
            }
        });

        airwaysbtn2.setBackground(new java.awt.Color(255, 102, 102));
        airwaysbtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        airwaysbtn2.setText("Airways");
        airwaysbtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        airwaysbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airwaysbtn2ActionPerformed(evt);
            }
        });

        signinbtn2.setBackground(new java.awt.Color(255, 102, 102));
        signinbtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signinbtn2.setText("Sign-in");
        signinbtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signinbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn2ActionPerformed(evt);
            }
        });

        aboutbtn.setBackground(new java.awt.Color(255, 102, 102));
        aboutbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        aboutbtn.setText("About");
        aboutbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aboutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutbtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tarvel pack001.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_1rsz_air-ticket-online_60196_image.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tpackbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(airticketbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(pediabtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(airwaysbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signinbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pediabtn2)
                    .addComponent(airwaysbtn2)
                    .addComponent(signinbtn2)
                    .addComponent(aboutbtn)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airticketbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void airticketbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airticketbtnActionPerformed


                  
                  airticket act = new airticket();
                  this.dispose();
                  act.setVisible(true); 
                  // TODO add your handling code here:
    }//GEN-LAST:event_airticketbtnActionPerformed

    private void jlblConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblConvertActionPerformed

        double Taka = Double.parseDouble(convert.getText());
        if(jcmbcurrency.getSelectedItem().equals("USA")){
         

            String cConvert1=String.format("$ %.3f", Taka*Dollar);
            converted.setText(cConvert1);
        }
        if(jcmbcurrency.getSelectedItem().equals("England")){
           

            String cConvert2=String.format("Pound %.2f", Taka*Pound);
            converted.setText(cConvert2);
        }
        if(jcmbcurrency.getSelectedItem().equals("India")){
            

            String cConvert3=String.format("Rupi %.2f", Taka*Rupi);
            converted.setText(cConvert3);
        }
 if(jcmbcurrency.getSelectedItem().equals("Nepal")){
            

            String cConvert4=String.format("Rupee %.2f", Taka*Rupee);
            converted.setText(cConvert4);
        }
  if(jcmbcurrency.getSelectedItem().equals("Thailand")){
            

            String cConvert5=String.format("Baht %.2f", Taka*Baht);
            converted.setText(cConvert5);
        }
   if(jcmbcurrency.getSelectedItem().equals("Malaysia")){
            

            String cConvert6=String.format("Ringgit %.2f", Taka*Ringgit);
            converted.setText(cConvert6);
        }
    if(jcmbcurrency.getSelectedItem().equals("Dubai")){
            

            String cConvert7=String.format("Dirham %.2f", Taka*Dirham);
            converted.setText(cConvert7);
        }
     if(jcmbcurrency.getSelectedItem().equals("Singapore")){
            

            String cConvert8=String.format("Singapore $ %.2f", Taka*sDollar);
            converted.setText(cConvert8);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblConvertActionPerformed

    private void convertioncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertioncloseActionPerformed
        convert.setText(null);
        converted.setText(null);
        jcmbcurrency.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_convertioncloseActionPerformed

    private void tpackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpackbtnActionPerformed
                    tourpackage trp = new tourpackage();
                  this.dispose();
                  trp.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_tpackbtnActionPerformed

    private void pediabtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pediabtn2ActionPerformed

            tourpedia tpda =new tourpedia();
            this.dispose();
            tpda.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_pediabtn2ActionPerformed

    private void airwaysbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airwaysbtn2ActionPerformed

        airticket act = new airticket();
        this.dispose();
        act.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_airwaysbtn2ActionPerformed

    private void signinbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn2ActionPerformed

        signin sin = new signin();
        this.dispose();
        sin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_signinbtn2ActionPerformed

    private void aboutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutbtnActionPerformed

            about at = new about();
                this.dispose();
                at.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(packageselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(packageselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(packageselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(packageselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new packageselect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutbtn;
    private javax.swing.JButton airticketbtn;
    private javax.swing.JButton airwaysbtn2;
    private javax.swing.JTextField convert;
    private javax.swing.JTextPane converted;
    private javax.swing.JButton convertionclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> jcmbcurrency;
    private javax.swing.JButton jlblConvert;
    private javax.swing.JButton pediabtn2;
    private javax.swing.JButton signinbtn2;
    private javax.swing.JButton tpackbtn;
    // End of variables declaration//GEN-END:variables

   
}
