/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.WindowEvent;

/**
 *
 * @author Farhad
 */
public class tourpackage extends javax.swing.JFrame {

    /**
     * Creates new form tourpackage
     */
    public tourpackage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bangladesh = new javax.swing.JButton();
        singapore = new javax.swing.JButton();
        dubai = new javax.swing.JButton();
        india = new javax.swing.JButton();
        nepal = new javax.swing.JButton();
        uk = new javax.swing.JButton();
        malaysia = new javax.swing.JButton();
        thailand = new javax.swing.JButton();
        usa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pediabtn2 = new javax.swing.JButton();
        airwaysbtn2 = new javax.swing.JButton();
        signinbtn2 = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_11red-wallpaper-1fd.jpg"))); // NOI18N

        bangladesh.setBackground(new java.awt.Color(0, 153, 51));
        bangladesh.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bangladesh.setForeground(new java.awt.Color(204, 0, 0));
        bangladesh.setText("Bangladesh");
        bangladesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangladeshActionPerformed(evt);
            }
        });

        singapore.setBackground(new java.awt.Color(0, 153, 153));
        singapore.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        singapore.setForeground(new java.awt.Color(204, 204, 204));
        singapore.setText("Singapore");
        singapore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singaporeActionPerformed(evt);
            }
        });

        dubai.setBackground(new java.awt.Color(255, 255, 204));
        dubai.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dubai.setForeground(new java.awt.Color(51, 51, 51));
        dubai.setText("Arab Emirates");
        dubai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dubaiActionPerformed(evt);
            }
        });

        india.setBackground(new java.awt.Color(153, 0, 153));
        india.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        india.setForeground(new java.awt.Color(0, 102, 255));
        india.setText("India");
        india.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiaActionPerformed(evt);
            }
        });

        nepal.setBackground(new java.awt.Color(204, 0, 51));
        nepal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        nepal.setForeground(new java.awt.Color(255, 255, 255));
        nepal.setText("Nepal");
        nepal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nepalActionPerformed(evt);
            }
        });

        uk.setBackground(new java.awt.Color(0, 102, 204));
        uk.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        uk.setForeground(new java.awt.Color(204, 0, 0));
        uk.setText("England");
        uk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukActionPerformed(evt);
            }
        });

        malaysia.setBackground(new java.awt.Color(255, 204, 204));
        malaysia.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        malaysia.setForeground(new java.awt.Color(0, 153, 0));
        malaysia.setText("Malaysia");
        malaysia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malaysiaActionPerformed(evt);
            }
        });

        thailand.setBackground(new java.awt.Color(255, 255, 255));
        thailand.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        thailand.setForeground(new java.awt.Color(153, 0, 51));
        thailand.setText("Thailand");
        thailand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thailandActionPerformed(evt);
            }
        });

        usa.setBackground(new java.awt.Color(51, 51, 255));
        usa.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        usa.setForeground(new java.awt.Color(255, 255, 0));
        usa.setText("U.S.A");
        usa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select  Destination");

        pediabtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pediabtn2.setText("Tour Pedia");
        pediabtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pediabtn2ActionPerformed(evt);
            }
        });

        airwaysbtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        airwaysbtn2.setText("Airways");
        airwaysbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airwaysbtn2ActionPerformed(evt);
            }
        });

        signinbtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signinbtn2.setText("Sign-in");
        signinbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn2ActionPerformed(evt);
            }
        });

        homebtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        homebtn.setText("Home");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bangladesh, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(singapore, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dubai, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thailand, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(india, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uk, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(malaysia, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(usa, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nepal, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(airwaysbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signinbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pediabtn2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homebtn)
                    .addComponent(pediabtn2)
                    .addComponent(airwaysbtn2)
                    .addComponent(signinbtn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bangladesh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(singapore, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dubai, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(india, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(uk, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(malaysia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nepal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thailand, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(usa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bangladeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangladeshActionPerformed


        bangladeshpack bkp = new bangladeshpack();
        this.dispose();
        bkp.setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_bangladeshActionPerformed

    private void singaporeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singaporeActionPerformed

            singapore sp = new singapore();
                   this.dispose();
                  sp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_singaporeActionPerformed

    private void dubaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dubaiActionPerformed


            dubai dp = new dubai();
                   this.dispose();
                  dp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_dubaiActionPerformed

    private void indiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiaActionPerformed
        
            india ip = new india();
                   this.dispose();
                  ip.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_indiaActionPerformed

    private void nepalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nepalActionPerformed

        nepal np = new nepal();
                   this.dispose();
                  np.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_nepalActionPerformed

    private void ukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukActionPerformed
              
                    uk uk = new uk();
                    this.dispose();
                    uk.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ukActionPerformed

    private void malaysiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malaysiaActionPerformed
            
            malaysia mp = new malaysia();
                   this.dispose();
                  mp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_malaysiaActionPerformed

    private void thailandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thailandActionPerformed
             thailand tp = new thailand();
                  this.dispose();
                  tp.setVisible(true);    

        // TODO add your handling code here:
    }//GEN-LAST:event_thailandActionPerformed

    private void usaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usaActionPerformed


            usa up = new usa();
                   this.dispose();
                  up.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_usaActionPerformed

    private void airwaysbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airwaysbtn2ActionPerformed

        airticket act = new airticket();
                  this.dispose();
                  act.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_airwaysbtn2ActionPerformed

    private void pediabtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pediabtn2ActionPerformed
tourpedia tpda =new tourpedia();
            this.dispose();
            tpda.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pediabtn2ActionPerformed

    private void signinbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn2ActionPerformed
                
                   signin sin = new signin();
                   this.dispose();
                  sin.setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_signinbtn2ActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed

         packageselect pct = new packageselect();
                   this.dispose();
                  pct.setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_homebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tourpackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tourpackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tourpackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tourpackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tourpackage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airwaysbtn2;
    private javax.swing.JButton bangladesh;
    private javax.swing.JButton dubai;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton india;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton malaysia;
    private javax.swing.JButton nepal;
    private javax.swing.JButton pediabtn2;
    private javax.swing.JButton signinbtn2;
    private javax.swing.JButton singapore;
    private javax.swing.JButton thailand;
    private javax.swing.JButton uk;
    private javax.swing.JButton usa;
    // End of variables declaration//GEN-END:variables


 

}
